Lint tkldev-changelog (shellcheck)

diff --git a/bin/tkldev-changelog b/bin/tkldev-changelog
--- a/bin/tkldev-changelog
+++ b/bin/tkldev-changelog
@@ -12,18 +12,18 @@
 # Free Software Foundation; either version 3 of the License, or (at your
 # option) any later version.
 
-fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
-warning() { echo "WARNING [$(basename $0)]: $@"; }
-info() { echo "INFO [$(basename $0)]: $@"; }
+fatal() { echo "FATAL [$(basename "$0")]: $*" 1>&2; exit 1; }
+warning() { echo "WARNING [$(basename "$0")]: $*"; }
+info() { echo "INFO [$(basename "$0")]: $*"; }
 
 usage() {
     if [[ $# -ne 0 ]]; then
-        echo "ERROR: $@"
+        echo "ERROR: $*"
         echo
         exit_code=1
     fi
 cat<<EOF
-Syntax: $(basename $0) [appliance-name]
+Syntax: $(basename "$0") [appliance-name]
 When run in the root directory of an appliance's source code, this script will
 create a new changelog entry at the top of an existing changelog file & opens
 the file for editing in vim.
@@ -70,26 +70,28 @@ Future plans:
     - support alternate text editors?
 
 EOF
-    exit $exit_code
+    exit "$exit_code"
 }
 
 [[ -z "$DEVDEBUG" ]] || set -x
 which dch > /dev/null || fatal "dch not found; please install 'devscripts'"
 which vim > /dev/null || fatal "vim not found; call yourself a developer?!?"
-[ -f changelog ] || fatal "no changelog in local dir"
+[[ -f changelog ]] || fatal "no changelog in local dir"
 
-APP=$(basename $PWD)
-COMMON_CHANGES="${FAB_PATH}/common/changes"
+APP=$(basename "$PWD")
 APP_CHANGELOGS=$(tkldev-makefile-info "$PWD/Makefile" -i \
     | grep -E "^${FAB_PATH}/common/" \
     | sed -En "s|^([a-z0-9/-]+)/mk/turnkey/*([a-z0-9-]+).mk|\1/changes/\2.changelog|p")
 
 if [ -z "$EXTRA_TEXT" ] && [ "$APP" != "core" ]; then
-    EXTRA_TEXT=$(tkldev-changelog-extractor "$PWD/changelog" "${FAB_PATH}/common/changes/turnkey.changelog" $APP_CHANGELOGS)
+    EXTRA_TEXT=$( \
+        tkldev-changelog-extractor "$PWD/changelog" \
+        "${FAB_PATH}/common/changes/turnkey.changelog" "$APP_CHANGELOGS" \
+    )
 fi
 
 EXTRA_TEXT_FILE="$(mktemp /tmp/tkldev-changelog.XXXXXX)"
-trap "rm -f $EXTRA_TEXT_FILE" EXIT
+trap 'rm -f $EXTRA_TEXT_FILE' EXIT
 echo "$EXTRA_TEXT" > "$EXTRA_TEXT_FILE"
 
 author_name=${DEBFULLNAME:-$FULLNAME}
@@ -97,29 +99,31 @@ author_email=${DEBEMAIL:-$EMAIL}
 if [[ -z "$author_name" ]] || [[ -z "$author_email" ]]; then
     unset changed
     if [[ -f "$HOME/.bashrc.d/tkldev-author" ]]; then
-        source $HOME/.bashrc.d/tkldev-author
+        # shellcheck source=/dev/null
+        source "$HOME/.bashrc.d/tkldev-author"
     fi
     if [[ -z "$author_name" ]] && [[ -z "$DEBFULLNAME" ]]; then
         warning "DEBFULLNAME (or FULLNAME) not set in env"
-        read -p "Enter fullname: " author_name
+        read -pr "Enter fullname: " author_name
         changed=true
     fi
     if [[ -z "$author_email" ]] && [[ -z "$DEBEMAIL" ]]; then
         warning "DEBEMAIL (or EMAIL) not set in env"
-        read -p "Enter email: " author_email
+        read -pr "Enter email: " author_email
         changed=true
     fi
-    if [[ "$changed" == 'true' ]]; then
-        read -p "Set permanently? (will save to $HOME/.bashrc.d/tkldev-author) [y]/n: " save
+    if [[ "$changed" == "true" ]]; then
+        read -pr "Set permanently? (will save to $HOME/.bashrc.d/tkldev-author) [y]/n: " save
         case $save in
             [yY]|yes|YES|"")
-                cat > $HOME/.bashrc.d/tkldev-author <<EOF
+                cat > "$HOME/.bashrc.d/tkldev-author" <<EOF
 # This file was generated by tkldev-changelog
 export DEBFULLNAME="$author_name"
 export DEBEMAIL="$author_email"
 EOF
-                chmod +x $HOME/.bashrc.d/tkldev-author
-                source $HOME/.bashrc.d/tkldev-author
+                chmod +x "$HOME/.bashrc.d/tkldev-author"
+                # shellcheck source=/dev/null
+                source "$HOME/.bashrc.d/tkldev-author"
                 ;;
             *)
                 export DEBFULLNAME="$author_name"
@@ -166,16 +170,16 @@ while [[ $# -gt 0 ]]; do
     esac
 done
 
-OLD_VER=$(head -1 changelog | cut -d' ' -f1 | sed "s|^.*${APP}-||")
-MAJ="$(echo ${OLD_VER} | cut -d. -f1)"
-MIN="$(echo ${OLD_VER} | cut -d. -f2)"
+OLD_VER=$(head -1 changelog | cut -d" " -f1 | sed "s|^.*${APP}-||")
+MAJ="$(echo "${OLD_VER}" | cut -d. -f1)"
+MIN="$(echo "${OLD_VER}" | cut -d. -f2)"
 
 if [[ -n "$new_min_set" ]] && [[ -n "$new_maj_set" ]]; then
     usage "-n|--new-minor & -N|--new-major can't both be set; doesn't make sense."
-elif [[ "$new" == 'minor' ]]; then
-    MIN="$(( $(echo ${OLD_VER} | cut -d. -f2) +1 ))"
-elif [[ "$new" == 'major' ]]; then
-    MAJ=$(( $MAJ +1 ))
+elif [[ "$new" == "minor" ]]; then
+    MIN="$(( $(echo "${OLD_VER}" | cut -d. -f2) +1 ))"
+elif [[ "$new" == "major" ]]; then
+    MAJ=$(( MAJ +1 ))
     MIN=0
 fi
 
@@ -190,9 +194,11 @@ fi
 if [[ -n "$set_author" ]]; then
     sed -i "0,\|^ -- |s|^.*> \(.*\)| -- $author_name <$author_email> \1|" changelog
 fi
-if [[ "$edit" == 'y' ]]; then
+if [[ "$edit" == "y" ]]; then
     if [[ -n "$new" ]]; then
-        dch --changelog changelog --release-heuristic log --package $NAME --newversion 1 --force-distribution turnkey --urgency low
+        dch --changelog changelog --release-heuristic log \
+            --package "$NAME" --newversion 1 --force-distribution turnkey \
+            --urgency low
         sed -i "3s|\*.*|\* |" changelog
         sed -e "4r ${EXTRA_TEXT_FILE}" -i changelog
     else
